CREATE TABLE CATEGORY
(
    NAME VARCHAR(36) NOT NULL,
    PRIMARY KEY (NAME)
);

CREATE TABLE ITEM
(
    ID          CHAR(36)    NOT NULL,
    NAME        VARCHAR(36) NOT NULL,
    CATEGORY_ID VARCHAR(36) NOT NULL,
    QUANTITY    INT,
    PRIMARY KEY (ID),
    CONSTRAINT FK_ITEM_CATEGORY
        FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (NAME)
);

CREATE TABLE MANAGER
(
    ID    CHAR(36)    NOT NULL,
    NAME  VARCHAR(36) NOT NULL,
    GRADE VARCHAR(36),
    PRIMARY KEY (ID)
);

CREATE TABLE IO_DETAIL
(
    ID         CHAR(36)    NOT NULL,
    IN_OUT     VARCHAR(36) NOT NULL,
    QUANTITY   INT         NOT NULL,
    MANAGER_ID CHAR(36)    NOT NULL,
    ITEM_ID    CHAR(36)    NOT NULL,
    IO_DATE    DATE        NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_IO_DETAIL_MANAGER
        FOREIGN KEY (MANAGER_ID) REFERENCES MANAGER (ID),
    CONSTRAINT FK_IO_DETAIL_ITEM
        FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ID)
        ON DELETE CASCADE
);
